Bubble sort
GrigorySmirnovSpb/HomeWorks_in_FSharp pull request #2
Opened 2024-09-24 06:38 UTC by GrigorySmirnovSpb

2024-09-29 19:58 UTC, gsvgit commented
Ну и тут тоже конфликты. Как и везде, похоже.

2024-10-03 04:58 UTC, gsvgit requested changes
Файлов, не относящихся к решению задачи, в реквесте (в том числе, в дифах) быть не должно.

2024-10-29 03:49 UTC, gsvgit requested changes
Бинарныйх файлов в реквесте быть не должно.

2024-10-29 12:42 UTC, GrigorySmirnovSpb reviewed
Delete BIN files

2024-11-14 11:55 UTC, gsvgit commented on src/Lib/Library.fs
> +        let mutable f: int = 1
Это кто такой?

2024-11-21 09:08 UTC, gsvgit commented on src/Lib/Library.fs
> +        let mutable f: int = 1
@GrigorySmirnovSpb Тут это. Вопрос без ответа.

2024-11-23 16:57 UTC, GrigorySmirnovSpb commented on src/Lib/Library.fs
> +        let mutable f: int = 1
У себя в локальном репозитории я его удалял и пушил, это я помню. Вот даже коммит снизу есть, я без понятия как он туда попал.

2024-11-23 16:58 UTC, GrigorySmirnovSpb commented on src/Lib/Library.fs
> +        let mutable f: int = 1
Или вопрос у другом?

2024-11-23 17:16 UTC, closed without merging