Quick sort
GrigorySmirnovSpb/HomeWorks_in_FSharp pull request #4
Opened 2024-09-24 06:38 UTC by GrigorySmirnovSpb

2024-09-29 19:57 UTC, gsvgit commented
Для начала надо сделать так, чтобы конфликтов не было.

2024-10-03 04:59 UTC, gsvgit requested changes
Файлов, не относящихся к решению задачи, в реквесте (в том числе, в дифах) быть не должно.

2024-10-29 03:55 UTC, gsvgit requested changes

2024-10-29 03:55 UTC, gsvgit commented on src/Lib/Library.fs
> +            arr <- QuickSort arr l j
Что-то тут странное происходит. Есть подозрение, что Вы не совсем поняли, как массивы работают.

2024-10-29 03:55 UTC, gsvgit commented on tests/Tests.fs
> +        let expected: int[] = [| 1; 2; 3; 4; 5; 6; 7; 8 |]
Сможем ли мы отсортировать пустой массив?

2024-10-29 03:55 UTC, gsvgit commented on src/Lib/Library.fs
> +    let rec QuickSort (arr1: int array) (l: int) (r: int) : int array =
Сортировка должна принимать только обрабатываемую коллекцию.

2024-11-09 14:52 UTC, GrigorySmirnovSpb commented on src/Lib/Library.fs
> +            arr <- QuickSort arr l j
Почему странное? В моем понимании я перезаписал массив arr (т.е. я отсортировал этот массив и перезаписал его)

2024-11-21 09:12 UTC, gsvgit reviewed
И соберите всё же задачки по домашкам. Чтобы был реквест на домашку.

2024-11-21 09:12 UTC, gsvgit commented on .gitignore
> +.vscode/launch.json
Как думаете, зачем оно изначально игнорировалось?

2024-11-21 09:12 UTC, gsvgit commented on tests/Tests.fs
> +    member this.TestMethodPassing1() =
Офигенные ясные и понятные названия у методов

2024-11-23 17:16 UTC, closed without merging