Create MergeSort
GrigorySmirnovSpb/HomeWorks_in_FSharp pull request #6
Opened 2024-09-30 14:57 UTC by GrigorySmirnovSpb

2024-09-30 18:37 UTC, gsvgit reviewed
И где описание к реквксту?

В следующий раз без описания нормального просто не будет проверяться.

2024-09-30 18:37 UTC, gsvgit commented on tests/Tests.fs
> +        let actual = MergeSort.MergeSort.MergeSort [|5; 1; 6; 4; 3; 7; 2|] compare
Больше MergeSort-ов хороших и разных!

2024-09-30 18:37 UTC, gsvgit commented on src/Lib/Library.fs
> +            then arr3 <- Array.concat [arr3; Array.sub arr2 j (Array.length arr2 - j)]
А можно ли как-то без конкатинаций обойтись?

2024-09-30 18:37 UTC, gsvgit commented on tests/Tests.fs
> +    member this.TestMethodPassing1 () =
Точно достаточно тестов?

2024-09-30 18:42 UTC, GrigorySmirnovSpb commented on tests/Tests.fs
> +        let actual = MergeSort.MergeSort.MergeSort [|5; 1; 6; 4; 3; 7; 2|] compare
)

2024-09-30 18:44 UTC, GrigorySmirnovSpb commented on src/Lib/Library.fs
> +            then arr3 <- Array.concat [arr3; Array.sub arr2 j (Array.length arr2 - j)]
Можно, но захотелось попробовать вот так. Немного новых функций не повредит моим знаниям)

2024-09-30 18:44 UTC, GrigorySmirnovSpb commented on tests/Tests.fs
> +    member this.TestMethodPassing1 () =
Знаю что маловато, сейчас добавлю ещё

2024-10-03 05:01 UTC, gsvgit commented on src/Lib/Library.fs
> +    let rec MergeSort (arr: 'a array) (compare):'a array =
Зачем ```compare``` в скобках?

2024-10-03 10:24 UTC, GrigorySmirnovSpb commented on src/Lib/Library.fs
> +    let rec MergeSort (arr: 'a array) (compare):'a array =
чтобы мне/вам было видно, что является параметрами функции

2024-10-03 10:55 UTC, gsvgit commented on src/Lib/Library.fs
> +    let rec MergeSort (arr: 'a array) (compare):'a array =
Вы не поверите.... Если пообвыкнуться с синтаксисом, то всё хорошо читается.

2024-10-29 04:00 UTC, gsvgit requested changes

2024-10-29 04:00 UTC, gsvgit commented on src/Lib/Library.fs
> +    let rec MergeSort (arr: 'a array) (compare):'a array =
Короче, чкобки не нужны

2024-10-29 04:00 UTC, gsvgit commented on src/Lib/Library.fs
> +            then arr3 <- Array.concat [arr3; Array.sub arr2 j (Array.length arr2 - j)]
Не надо так. Тем более, что Вы знаете длину результата.

2024-10-29 04:00 UTC, gsvgit commented on tests/Tests.fs
> +        let actual = MergeSort.MergeSort.MergeSort [|5; 1; 6; 4; 3; 7; 2|] compare
И всё же. У Вас ячно что-то не так с наименованием.

2024-10-29 04:00 UTC, gsvgit commented on tests/Tests.fs
> +    member this.TestMethodPassing5() =
А пустой отсортировать сможем?

2024-11-14 12:02 UTC, gsvgit reviewed
А ещё не надо запрашивать ревью, а потом коммитить. Сперва убедились, что вот прям всё готово, потом запрашиваете.

2024-11-14 12:02 UTC, gsvgit commented on .vscode/launch.json
> +    "configurations": [
Что это и для чего?

2024-11-27 09:14 UTC, closed without merging